StarAirEdi/Models/DeliveryOrder.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarAirEdi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DeliveryOrder
    {
        public long Id { get; set; }
        [Display(Name = "Delivery Order No.")]
        public string DeliverOrderNo { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> JobDate { get; set; }
        public string CarnNo { get; set; }
        public string IgmNo { get; set; }
        public string IgmYear { get; set; }
        public string FlightNo { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FlightDate { get; set; }
        public Nullable<System.TimeSpan> FlightTime { get; set; }
        public string HawbNo { get; set; }
        public string PortOfOrigin { get; set; }
        public string PortOfDest { get; set; }
        public Nullable<int> TotalPkg { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public string ItemDescription { get; set; }
        public string ConsigneeName { get; set; }
        public string MawbNo { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}

StarAirEdi/Controllers/DeliveryOrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StarAirEdi.Models;
using Microsoft.AspNet.Identity;
using PagedList;
using System.Globalization;

namespace StarAirEdi.Controllers
{
    [Authorize]
    public class DeliveryOrderController : Controller
    {
        private StarEdiAirEntities db = new StarEdiAirEntities();

        // GET: /DeliveryOrder/
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            var profileData = (UserProfileSessionData)Session["UserProfile"];
             if (profileData != null)
             {
                 var deliveryOrders = db.DeliveryOrders.Where(p => p.CreatedBy == profileData.UserId);
                 ViewBag.CurrentSort = sortOrder;
                 ViewBag.DOSortParm = String.IsNullOrEmpty(sortOrder) ? "DeliveryNo_Desc" : "";

                 if (searchString != null)
                 {
                     page = 1;
                 }
                 else
                 {
                     searchString = currentFilter;
                 }

                 ViewBag.CurrentFilter = searchString;

                 if (!String.IsNullOrEmpty(searchString))
                 {
                     deliveryOrders = deliveryOrders.Where(s => s.MawbNo.Contains(searchString)
                                             || s.DeliverOrderNo.Contains(searchString) || s.HawbNo.Contains(searchString));
                 }
                 switch (sortOrder)
                 {
                     case "DeliveryNo_Desc":
                         deliveryOrders = deliveryOrders.OrderByDescending(s => s.MawbNo);
                         break;
                     default:
                         deliveryOrders = deliveryOrders.OrderByDescending(s => s.CreatedOn);
                         break;
                 }
                 int pageSize = 8;
                 int pageNumber = (page ?? 1);

                 return View(deliveryOrders.ToPagedList(pageNumber, pageSize));
                 //return View(deliveryOrders);
             }
             else
             {
                 return RedirectToAction("Location", "Home");
             }
             
        }
        // GET: /DeliveryOrder/
        public ActionResult SelectHawb(string mawbId)
        {
            var mawbId1 = Convert.ToInt32(mawbId);
            var Mawblist = db.Mawbs.ToList().Select(rr => new SelectListItem { Value = rr.Id.ToString(), Text = rr.MawbNo }).ToList();
            var list = db.Hawbs.Where(l => l.MawbId == mawbId1).ToList().Select(rr => new SelectListItem { Value = rr.Id.ToString(), Text = rr.HawbNo }).ToList();
            ViewBag.MawbId = Mawblist;
            ViewBag.HawbId = list;
            return Json(list);
        }
        // GET: /DeliveryOrder/
        public ActionResult PrintDeliveryOrder(long? Id)
        {
            DeliveryOrder deliveryorder = db.DeliveryOrders.Find(Id);
            var userId = User.Identity.GetUserId();
            var profile = db.UserProfiles.Where(p => p.UserId == userId).FirstOrDefault();
            ViewBag.AgentName = profile.AgentName;
            ViewBag.Address1 = profile.Address1;
            ViewBag.Address2 = profile.Address2;
            //var hawb = db.Hawbs.Find(HawbId);

            return View(deliveryorder);
        }

        // GET: /DeliveryOrder/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DeliveryOrder deliveryorder = db.DeliveryOrders.Find(id);
            if (deliveryorder == null)
            {
                return HttpNotFound();
            }
            return View(deliveryorder);
        }

        // GET: /DeliveryOrder/Create
        public ActionResult Create()
        {
             var profileData = (UserProfileSessionData)Session["UserProfile"];
             if (profileData != null)
             {
                 var Mawblist = db.Mawbs.Where(p => p.CreatedBy == profileData.UserId).ToList().Select(rr => new SelectListItem { Value = rr.Id.ToString(), Text = rr.MawbNo }).ToList();
                 var Hawblist = db.Hawbs.Where(l => l.MawbId == 0).ToList().Select(rr => new SelectListItem { Value = rr.Id.ToString(), Text = rr.HawbNo }).ToList();
                 ViewBag.MawbId = Mawblist;
                 ViewBag.HawbId = Hawblist;
                 return View();
             }
             else
             {
                 return RedirectToAction("Location", "Home");
             }
        }

        // POST: /DeliveryOrder/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int? mawbId, int? HawbId,[Bind(Include="Id,DeliverOrderNo,JobDate,CarnNo,IgmNo,IgmYear,FlightNo,FlightDate,FlightTime,MawbNo,HawbNo,PortOfOrigin,PortOfDest,TotalPkg,GrossWeight,ItemDescription,ConsigneeName,CreatedBy,CreatedOn")] DeliveryOrder deliveryorder)
        {
            if (string.IsNullOrEmpty(deliveryorder.DeliverOrderNo))
            {
                var profileData = (UserProfileSessionData)Session["UserProfile"];
                if (profileData != null)
                {
                    var mawbSelectList = new SelectList(db.Mawbs.Where(p => p.CreatedBy == profileData.UserId), "Id", "MawbNo", mawbId);
                    ViewBag.MawbId = mawbSelectList;
                    ViewBag.HawbId = new SelectList(db.Hawbs, "Id", "HawbNo", HawbId);
                    var datetime = DateTime.Now;
                    var userId = User.Identity.GetUserId();
                    var hawb = db.Hawbs.Find(HawbId);
                    var profile = db.UserProfiles.Where(p => p.UserId == userId).FirstOrDefault();
                    deliveryorder.PortOfDest = hawb.PortOfDest;
                    deliveryorder.PortOfOrigin = hawb.PortOfOrigin;
                    deliveryorder.TotalPkg = Convert.ToInt32(hawb.NoOfPkg);
                    deliveryorder.JobDate = DateTime.Now;//DateTime.Parse(DateTime.Now.ToString("MM/dd/yyyy", CultureInfo.InvariantCulture));
                    deliveryorder.GrossWeight = hawb.Weight;
                    deliveryorder.ItemDescription = hawb.Description;
                    deliveryorder.MawbNo = mawbSelectList.Where(p => p.Value == mawbId.ToString()).First().Text;
                    deliveryorder.HawbNo = hawb.HawbNo;
                    deliveryorder.CarnNo = profile.ConsolAgentId;
                    deliveryorder.DeliverOrderNo = string.Format("{0}{1}", "DO-", db.DeliveryOrders.Count() + 1);
                    deliveryorder.CreatedBy = profileData.UserId;
                    deliveryorder.CreatedOn = DateTime.Now;
                }
                else
                {
                    return RedirectToAction("Location", "Home");
                }
            }
            else
            {
                if (ModelState.IsValid)
                {
                    db.DeliveryOrders.Add(deliveryorder);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            return View(deliveryorder);
        }

        // GET: /DeliveryOrder/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DeliveryOrder deliveryorder = db.DeliveryOrders.Find(id);
            deliveryorder.CreatedOn = DateTime.Now;
            if (deliveryorder == null)
            {
                return HttpNotFound();
            }
            return View(deliveryorder);
        }

        // POST: /DeliveryOrder/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,DeliverOrderNo,JobDate,CarnNo,IgmNo,IgmYear,FlightNo,FlightDate,FlightTime,MawbNo,HawbNo,PortOfOrigin,PortOfDest,TotalPkg,GrossWeight,ItemDescription,ConsigneeName,CreatedBy,CreatedOn")] DeliveryOrder deliveryorder)
        {
            if (ModelState.IsValid)
            {
                db.Entry(deliveryorder).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(deliveryorder);
        }

        // GET: /DeliveryOrder/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DeliveryOrder deliveryorder = db.DeliveryOrders.Find(id);
            if (deliveryorder == null)
            {
                return HttpNotFound();
            }
            return View(deliveryorder);
        }

        // POST: /DeliveryOrder/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            DeliveryOrder deliveryorder = db.DeliveryOrders.Find(id);
            db.DeliveryOrders.Remove(deliveryorder);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

StarAirEdi/Views/DeliveryOrder/Create.cshtml
@model StarAirEdi.Models.DeliveryOrder

@{
    ViewBag.Title = "Create";
}

<script language="javascript" type="text/javascript">
    function SelectHawb(_mawbId) {
        debugger;
        var procemessage = "<option value='0'> Please wait...</option>";
        $("#ddlhawb").html(procemessage).show();
        var url = "/DeliveryOrder/SelectHawb/";

        $.ajax({
            url: url,
            data: { mawbId: _mawbId },
            cache: false,
            type: "POST",
            success: function (data) {
                debugger;
                var markup = "<option value='0'>Select Hawb</option>";
                for (var x = 0; x < data.length; x++) {
                    markup += "<option value=" + data[x].Value + ">" + data[x].Text + "</option>";
                }
                $("#HawbId").html(markup).show();
            },
            error: function (reponse) {
                alert("error : " + reponse);
            }
        });

    }
</script>
<hr />
@using (Html.BeginForm("Create", "DeliveryOrder"))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <p>
        Select Mawb No.: @Html.DropDownList("MawbId", (IEnumerable<SelectListItem>)ViewBag.MawbId,"Select MAWB", new { @id = "ddlmawb", @style = "width:175px;height:25px", @onchange = "javascript:SelectHawb(this.value);" })
       
        Select Hawb No.: @Html.DropDownList("HawbId",(IEnumerable<SelectListItem>)ViewBag.HawbId, "Select HAWB", new { style = "width:175px;height:25px" }))
        
        @*<select id="ddlhawb" name="ddlhawb" style="width: 200px"></select>*@
        <input type="submit" value="Submit" />
    </p>
}
<hr />

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.HawbNo)
    @Html.HiddenFor(model => model.MawbNo)
    @Html.HiddenFor(model => model.CreatedBy)
    @Html.HiddenFor(model => model.CreatedOn)
    <div class="form-horizontal">
 
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.DeliverOrderNo, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.DeliverOrderNo)
                @Html.ValidationMessageFor(model => model.DeliverOrderNo)
            </div>
            @Html.LabelFor(model => model.JobDate, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.JobDate, new { htmlAttributes = new { @class = "date-picker" } })
                @Html.ValidationMessageFor(model => model.JobDate)
            </div>
        </div>

        <div class="form-group">
            @*@Html.LabelFor(model => model.HawbNo, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.HawbNo)
                @Html.ValidationMessageFor(model => model.HawbNo)
            </div>*@
            @Html.LabelFor(model => model.PortOfOrigin, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.PortOfOrigin)
                @Html.ValidationMessageFor(model => model.PortOfOrigin)
            </div>
            @Html.LabelFor(model => model.PortOfDest, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.PortOfDest)
                @Html.ValidationMessageFor(model => model.PortOfDest)
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.PortOfOrigin, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PortOfOrigin)
                @Html.ValidationMessageFor(model => model.PortOfOrigin)
            </div>
        </div>*@

        <div class="form-group">

            @Html.LabelFor(model => model.TotalPkg, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.TotalPkg)
                @Html.ValidationMessageFor(model => model.TotalPkg)
            </div>
            @Html.LabelFor(model => model.GrossWeight, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.GrossWeight)
                @Html.ValidationMessageFor(model => model.GrossWeight)
            </div>
        </div>

        <div class="form-group">
          
            @Html.LabelFor(model => model.IgmNo, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.IgmNo)
                @Html.ValidationMessageFor(model => model.IgmNo)
            </div>
            @Html.LabelFor(model => model.IgmYear, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.IgmYear)
                @Html.ValidationMessageFor(model => model.IgmYear)
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.IgmNo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IgmNo)
                @Html.ValidationMessageFor(model => model.IgmNo)
            </div>
        </div>*@

        <div class="form-group">
           
            @Html.LabelFor(model => model.FlightNo, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.FlightNo)
                @Html.ValidationMessageFor(model => model.FlightNo)
            </div>
            @Html.LabelFor(model => model.FlightDate, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.FlightDate, new { htmlAttributes = new { @class = "date-picker" } })
                @Html.ValidationMessageFor(model => model.FlightDate)
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.FlightNo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FlightNo)
                @Html.ValidationMessageFor(model => model.FlightNo)
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.FlightTime, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.FlightTime)
                @Html.ValidationMessageFor(model => model.FlightTime)
            </div>
            @Html.LabelFor(model => model.ItemDescription, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.ItemDescription)
                @Html.ValidationMessageFor(model => model.ItemDescription)
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.ConsigneeName, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.ConsigneeName)
                @Html.ValidationMessageFor(model => model.ConsigneeName)
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.ItemDescription, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ItemDescription)
                @Html.ValidationMessageFor(model => model.ItemDescription)
            </div>
        </div>*@

        <div class="form-group">
            
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

StarAirEdi/Views/DeliveryOrder/Delete.cshtml
@model StarAirEdi.Models.DeliveryOrder

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DeliveryOrder</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DeliverOrderNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliverOrderNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CarnNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CarnNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IgmNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IgmNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IgmYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IgmYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FlightNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FlightNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FlightDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FlightDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FlightTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FlightTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HawbNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HawbNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PortOfOrigin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PortOfOrigin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PortOfDest)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PortOfDest)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalPkg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalPkg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GrossWeight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GrossWeight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ItemDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ItemDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ConsigneeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ConsigneeName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

StarAirEdi/Views/DeliveryOrder/Index.cshtml
@model PagedList.IPagedList<StarAirEdi.Models.DeliveryOrder>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />


@{
    ViewBag.Title = "Index";
}

<h3>
    @Html.ActionLink("Add DO", "Create")
</h3>
@using (Html.BeginForm("Index", "DeliveryOrder", FormMethod.Get))
{
    <p>
        Find by Mawb or Hawb No.: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Delivery Order No.", "Index", new { sortOrder = ViewBag.DOSortParm, currentFilter = ViewBag.CurrentFilter })
            @*@Html.DisplayNameFor(model => model.DeliverOrderNo)*@
        </th>
        <th>
            @Html.Label("Job Date")
            @*@Html.DisplayNameFor(model => model.JobDate)*@
        </th>
      
        <th>
            @Html.Label("Igm No")
            @*@Html.DisplayNameFor(model => model.IgmNo)*@
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.IgmYear)
        </th>*@
        <th>
            @Html.Label("Flight No")
            @*@Html.DisplayNameFor(model => model.FlightNo)*@
        </th>
        
        <th>
            @Html.Label("Master AWB")
        </th>

        <th>
            @Html.Label("House AWB")
            @*@Html.DisplayNameFor(model => model.HawbNo)*@
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.PortOfOrigin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PortOfDest)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TotalPkg)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GrossWeight)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ItemDescription)
        </th>*@
        <th>
            @Html.Label("Consignee Name")
            @*@Html.DisplayNameFor(model => model.ConsigneeName)*@
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DeliverOrderNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JobDate)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.CarnNo)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.IgmNo)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.IgmYear)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.FlightNo)
        </td>
       
        <td>
            @Html.DisplayFor(modelItem => item.MawbNo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HawbNo)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.PortOfOrigin)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PortOfDest)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TotalPkg)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GrossWeight)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ItemDescription)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.ConsigneeName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Print", "PrintDeliveryOrder", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>
  <br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))