StarAirEdi/Models/ChecklistViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace StarAirEdi.Models
{
    public class ChecklistViewModels
    {
        private DateTime? _startDate;
        private DateTime? _endDate;
        public ChecklistViewModels()
        {
            _startDate = DateTime.Now;
            _endDate = DateTime.Now;
        }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> StartDate { get { return _startDate; } set { _startDate = value;} }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> EndDate { get { return _endDate; } set { _endDate = value; } }
        public System.String User { get; set; }
        public IEnumerable<Mawb> mawbs { get; set; }
        public IEnumerable<Hawb> hawbs { get; set; }
        public IEnumerable<UserProfile> UserProfiles { get; set; }
        public IEnumerable<Location> locations { get; set; }
        public virtual Mawb Mawb { get; set; }
    }
}

StarAirEdi/Controllers/CheckListController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StarAirEdi.Models;
using Microsoft.AspNet.Identity;
using PagedList;

namespace StarAirEdi.Controllers
{
    [Authorize]
    public class CheckListController : Controller
    {
        private StarEdiAirEntities db = new StarEdiAirEntities();
        private ChecklistViewModels checklistviewmodel = new ChecklistViewModels();
        DateTime limitDate = DateTime.Now.AddDays(-10);
        // GET: /Mawb/
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            //var mawbs = db.Mawbs.Include(m => m.Location);
            var profileData = (UserProfileSessionData)Session["UserProfile"];
            if (profileData != null)
            {
                var mawbs = db.Mawbs.Where(p => p.CreatedBy == profileData.UserId && p.CreatedOn > limitDate);
                ViewBag.MawbId = new SelectList(mawbs.OrderByDescending(a => a.CreatedOn), "Id", "MawbNo");
                ViewBag.CurrentSort = sortOrder;
                ViewBag.MawbSortParm = String.IsNullOrEmpty(sortOrder) ? "MawbNo_Desc" : "";

                if (searchString != null)
                {
                    page = 1;
                    mawbs = db.Mawbs.Where(p => p.CreatedBy == profileData.UserId);
                }
                else
                {
                    searchString = currentFilter;
                }

                ViewBag.CurrentFilter = searchString;

                if (!String.IsNullOrEmpty(searchString))
                {
                    mawbs = mawbs.Where(s => s.MawbNo.Contains(searchString)
                                            || s.PortOfOrg.Contains(searchString));
                }
                switch (sortOrder)
                {
                    case "MawbNo_Desc":
                        mawbs = mawbs.OrderByDescending(s => s.MawbNo);
                        break;
                    default:
                        mawbs = mawbs.OrderByDescending(s => s.CreatedOn);
                        break;
                }
                int pageSize = 8;
                int pageNumber = (page ?? 1);

                checklistviewmodel.mawbs = mawbs;
                return View(mawbs.ToPagedList(pageNumber, pageSize));
                //return View(mawbs.ToList());
            }
            else
            {
                return RedirectToAction("Location", "Home");
            }

        }
        
        //
        // GET: /CheckList/
        //public ActionResult Index()
        //{
        //   var profileData = (UserProfileSessionData)Session["UserProfile"];
        //   if(profileData==null)
        //       return RedirectToAction("Location", "Home");
        //   var mawbs = db.Mawbs.Where(p => p.CreatedBy == profileData.UserId);
        //   ViewBag.MawbId = new SelectList(mawbs.OrderByDescending(a => a.CreatedOn), "Id", "MawbNo");
        //   var mawbId = 0;
        //   ChecklistViewModels checklistviewmodel = new ChecklistViewModels();
        //   checklistviewmodel.mawbs = db.Mawbs.Where(h => h.Id == mawbId);
        //   checklistviewmodel.hawbs = db.Hawbs.Where(h => h.MawbId == mawbId);
        //   return View(checklistviewmodel);
        //}

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(FormCollection collection)
        {
            long mawbId = long.Parse(collection["MawbId"].ToString());
            if (mawbId!=0)
                return RedirectToAction("Details", new { id = mawbId });

            var profileData = (UserProfileSessionData)Session["UserProfile"];
            if (profileData == null)
                return RedirectToAction("Index", "Home");
            var mawbs = db.Mawbs.Where(p => p.CreatedBy == profileData.UserId);
            ViewBag.MawbId = new SelectList(mawbs.OrderByDescending(a => a.CreatedOn), "Id", "MawbNo", mawbId);
            return View();
        }

        // GET: /CheckList/
        public ActionResult AccountStatement()
        {
            var profileData = (UserProfileSessionData)Session["UserProfile"];
            if (profileData == null)
                return RedirectToAction("Location", "Home");
            //var mawbs = db.Mawbs.Where(p => p.CreatedBy == profileData.UserId);
            //ViewBag.MawbId = new SelectList(mawbs.OrderByDescending(a => a.CreatedOn), "Id", "MawbNo");
            //var mawbId = 0;
            //ChecklistViewModels checklistviewmodel = new ChecklistViewModels();
            //checklistviewmodel.mawbs = db.Mawbs.Where(h => h.Id == mawbId);
            //checklistviewmodel.hawbs = db.Hawbs.Where(h => h.MawbId == mawbId);
            return View(checklistviewmodel);
            //return View(checklistviewmodel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AccountStatement(FormCollection collection)
        {
            
            var startDate = DateTime.Parse(collection["StartDate"]);
            var endDate = DateTime.Parse(collection["EndDate"]);
            if (startDate !=null)
                return RedirectToAction("AccountStatementDetails", new { startDate = startDate, endDate=endDate.AddHours(24).AddSeconds(-1)});

            var profileData = (UserProfileSessionData)Session["UserProfile"];
            if (profileData == null)
                return RedirectToAction("Index", "Home");
            return View();
        }

        //
        // GET: /CheckList/Details/5
        public ActionResult AccountStatementDetails(DateTime startDate, DateTime endDate)
        {
            var currentUser=User.Identity.GetUserId();
             var mawbs = (from m in db.Mawbs
                          join a in db.UserProfiles on m.CreatedBy.Value equals a.Id
                          join u in db.AspNetUsers on a.UserId equals u.Id
                          where u.Id == currentUser && m.TransmittedOn >= startDate && m.TransmittedOn <= endDate
                        select m);

            ChecklistViewModels checklistviewmodel = new ChecklistViewModels();

            checklistviewmodel.mawbs = mawbs;
            //checklistviewmodel.mawbs = db.Mawbs.Where(h => h.TransmittedOn >=startDate && h.TransmittedOn <=endDate);
            checklistviewmodel.hawbs = db.Hawbs.Where(h => h.CreatedOn >= startDate && h.CreatedOn <= endDate);
            ViewBag.StartDate = startDate;
            ViewBag.EndDate = endDate;
            return View(checklistviewmodel);
        }

        // GET: /CheckList/
        public ActionResult AccountStatementUser()
        {
            var profileData = (UserProfileSessionData)Session["UserProfile"];
            if (profileData == null)
                return RedirectToAction("Location", "Home");
            ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "UserName");
            //return View();
            return View(checklistviewmodel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AccountStatementUser(FormCollection collection)
        {

            var startDate = DateTime.Parse(collection["StartDate"]);
            var endDate = DateTime.Parse(collection["EndDate"]);
            var user = collection["UserId"].ToString();
            if (startDate != null)
                return RedirectToAction("AccountStatementUserDetails", new { startDate = startDate, endDate = endDate.AddHours(24).AddSeconds(-1),user=user });

            var profileData = (UserProfileSessionData)Session["UserProfile"];
            if (profileData == null)
                return RedirectToAction("Index", "Home");
            return View();
        }

        //
        // GET: /CheckList/Details/5
        public ActionResult AccountStatementUserDetails(DateTime startDate, DateTime endDate, String user)
        {
            var currentUser = user;
            var mawbs = (from m in db.Mawbs
                         join a in db.UserProfiles on m.CreatedBy.Value equals a.Id
                         join u in db.AspNetUsers on a.UserId equals u.Id
                         where a.UserId == currentUser && m.TransmittedOn >= startDate && m.TransmittedOn <= endDate
                         select m);

            ChecklistViewModels checklistviewmodel = new ChecklistViewModels();

            checklistviewmodel.mawbs = mawbs;
            //checklistviewmodel.mawbs = db.Mawbs.Where(h => h.TransmittedOn >=startDate && h.TransmittedOn <=endDate);
            checklistviewmodel.hawbs = db.Hawbs.Where(h => h.CreatedOn >= startDate && h.CreatedOn <= endDate);
            ViewBag.StartDate = startDate;
            ViewBag.EndDate = endDate;
            ViewBag.UserId = db.AspNetUsers.Find(user).UserName;
            return View(checklistviewmodel);
        }


        //
        // GET: /CheckList/Details/5
        public ActionResult Details(int id)
        {
            ChecklistViewModels checklistviewmodel = new ChecklistViewModels();
            checklistviewmodel.mawbs = db.Mawbs.Where(h => h.Id == id);
            checklistviewmodel.hawbs = db.Hawbs.Where(h => h.MawbId == id);
            //.ToList<Mawb>();
            //checklistviewmodel.hawbs = db.Hawbs.ToList<Hawb>();
            
            return View(checklistviewmodel);
        }

        //
        // GET: /CheckList/Create
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /CheckList/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /CheckList/Edit/5
        public ActionResult Edit(int id)
        {

StarAirEdi/Views/CheckList/AccountStatement.cshtml
@model StarAirEdi.Models.ChecklistViewModels

@{
    ViewBag.Title = "AccountStatement";
    
}

<h3>Account Statement</h3>


@using (Html.BeginForm())
{
     @Html.AntiForgeryToken()
    <br /><br />
    <div class="form-vertical">
        <div class="form-group">
            <div>
                From Date: @Html.EditorFor(model=>model.StartDate, new { htmlAttributes = new { @class = "date-picker"} })
                To Date:   @Html.EditorFor(model =>model.EndDate, new { htmlAttributes = new { @class = "date-picker" } })
                <input type="submit" value="Search" />
            </div>
        </div>
        
    </div>
}

StarAirEdi/Views/CheckList/AccountStatementDetails.cshtml
@model StarAirEdi.Models.ChecklistViewModels

@{
    ViewBag.Title = "Account Statement Details";
}

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
    <title></title>
</head>
<br />
<body>
    <div align="center"> 
        <b> 
        Account Statement<br />
        Period ( @ViewBag.StartDate And @ViewBag.EndDate) 
        <br />
        </b>
    </div>
 
    <table class="table table-bordered">
        @foreach (var item in Model.mawbs)
        {
            <tr>
                <th>
                    @Html.DisplayNameFor(modelItemName => item.MawbNo)
                </th>
                <th>
                    @Html.DisplayNameFor(modelItemName => item.CreatedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(modelItemName => item.TransmittedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(modelItemName => item.CustomHouseCode)
                </th>
                <th>
                    @Html.DisplayNameFor(modelItemName => item.ConsolAgentId)
                </th>
                <th>
                    @Html.DisplayName("No Of HAWB")
                </th>
            </tr>
            break;
        }
        @foreach (var item in Model.mawbs)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MawbNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedOn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TransmittedOn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomHouseCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ConsolAgentId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Hawbs.Count)
                </td>
                
            </tr>
        }
        <tr>
            <th>Total Mawb : </th>
            <th>@Model.mawbs.Count()</th>
            <th></th>
            <th></th>
            <th>Total Hawb : </th>
            <th>@Model.mawbs.Sum(s => s.Hawbs.Count())</th>
        </tr>
    </table>

  
    <script type="text/javascript">
        if (window.print) {
            document.write('<form> <center>'
            + '<input type=button name=print id="b1" value=" Print Page "  '
            + 'onClick="printpage()">  </center></form>');
        }
        function printpage() {
            document.getElementById('b1').style.display = 'none';
            window.print();
        }
        // End -->
    </script>
</body>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StarAirEdi/Views/CheckList/AccountStatementUser.cshtml
@model StarAirEdi.Models.ChecklistViewModels

@{
    ViewBag.Title = "AccountStatementUser";
}

<h3>Account Statement By User</h3>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <br /><br />
    <div class="form-vertical">
        <div class="form-group">
            <div class="col-md-12">
                <p>User: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@Html.DropDownList("UserId", (IEnumerable<SelectListItem>)ViewBag.UserId, "Select User", new { style = "width:175px;height:25px" })</p>
                From Date:@Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "date-picker" } })
                To Date  :@Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "date-picker" } })
                <input type="submit" value="Search" />
            </div>
        </div>

    </div>
}

StarAirEdi/Views/CheckList/AccountStatementUserDetails.cshtml
@model StarAirEdi.Models.ChecklistViewModels

@{
    //Layout = null;
    ViewBag.Title = "Account Statement Details By User";
}

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
    <title></title>
</head>
<br />
<body>
    <div align="center">
        <b>
            Account Statement For <b>@ViewBag.UserId</b><br />
            Period ( @ViewBag.StartDate And @ViewBag.EndDate)
            <br />
        </b>
    </div>

    <table class="table table-bordered">
        @foreach (var item in Model.mawbs)
        {
            <tr>
                <th>
                    @Html.DisplayNameFor(modelItemName => item.MawbNo)
                </th>
                <th>
                    @Html.DisplayNameFor(modelItemName => item.CreatedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(modelItemName => item.TransmittedOn)
                </th>
                <th>
                    @Html.DisplayNameFor(modelItemName => item.CustomHouseCode)
                </th>
                <th>
                    @Html.DisplayNameFor(modelItemName => item.ConsolAgentId)
                </th>
                <th>
                    @Html.DisplayName("No Of HAWB")
                </th>
            </tr>
            break;
        }
        @foreach (var item in Model.mawbs)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MawbNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedOn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TransmittedOn)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CustomHouseCode)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ConsolAgentId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Hawbs.Count)
                </td>

            </tr>
        }
        <tr>
            <th>Total Mawb : </th>
            <th>@Model.mawbs.Count()</th>
            <th></th>
            <th></th>
            <th>Total Hawb : </th>
            <th>@Model.mawbs.Sum(s => s.Hawbs.Count())</th>
        </tr>

    </table>


    <script type="text/javascript">
        if (window.print) {
            document.write('<form> <center>'
            + '<input type=button name=print id="b1" value=" Print Page "  '
            + 'onClick="printpage()">  </center></form>');
        }
        function printpage() {
            document.getElementById('b1').style.display = 'none';
            window.print();
        }
        // End -->
    </script>
</body>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StarAirEdi/Views/CheckList/Details.cshtml
@model StarAirEdi.Models.ChecklistViewModels

@{
    ViewBag.Title = "CheckList Details";
}

<h3>CheckList Details</h3>

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
    <title></title>
    
</head>
<body>
    <table class="table table-bordered">
        @foreach (var item in Model.mawbs)
        {
            <tr>
                <th>
                    @Html.DisplayNameFor(modelItemName => item.MawbNo)
                </th>
                <th>
                    @Html.DisplayNameFor(modelItemName => item.PortOfOrg)
                </th>
                <th>
                    @Html.DisplayNameFor(modelItemName => item.PortOfDest)
                </th>
                <th>
                    @Html.DisplayNameFor(modelItemName => item.TotalPkg)
                </th>
                <th>
                    @Html.DisplayNameFor(modelItemName => item.GrossWeight)
                </th>
                <th>
                    @Html.DisplayNameFor(modelItemName => item.ItemDesc)
                </th>

            </tr>
        }
        @foreach (var item in Model.mawbs)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MawbNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PortOfOrg)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PortOfDest)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalPkg)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GrossWeight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ItemDesc)
                </td>
            </tr>
        }

    </table>

    <table class="table table-bordered">
        @foreach (var item in Model.hawbs)
        {
            <tr>
                <th>
                    @Html.DisplayNameFor(model => item.HawbNo)
                </th>
                <th>
                    @Html.DisplayNameFor(model => item.PortOfOrigin)
                </th>
                <th>
                    @Html.DisplayNameFor(model => item.PortOfDest)
                </th>
                <th>
                    @Html.DisplayNameFor(model => item.NoOfPkg)
                </th>
                <th>
                    @Html.DisplayNameFor(model => item.Weight)
                </th>
                <th>
                    @Html.DisplayNameFor(model => item.Description)
                </th>
                
            </tr>
            break;
        }
        @foreach (var hawbItem in Model.hawbs)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => hawbItem.HawbNo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => hawbItem.PortOfOrigin)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => hawbItem.PortOfDest)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => hawbItem.NoOfPkg)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => hawbItem.Weight)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => hawbItem.Description)
                </td>
                
            </tr>
        }
        <tr>
            <td></td>
            <td></td>
            <th>Total</th>
            <th>@Model.hawbs.Sum(s=>s.NoOfPkg)</th>
            <th>@Model.hawbs.Sum(s => s.Weight)</th>
        </tr>

    </table>
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
    <script type="text/javascript">
        if (window.print) {
            document.write('<form> <center>'
            + '<input type=button name=print id="b1" value=" Print Page "  '
            + 'onClick="printpage()">  </center></form>');
        }
        function printpage() {
            document.getElementById('b1').style.display = 'none';
            window.print();
        }
        // End -->
    </script>
</body>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StarAirEdi/Views/CheckList/Index.cshtml
@model PagedList.IPagedList<StarAirEdi.Models.Mawb>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />


@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            <div class="col-md-6">
                <b>Mawb No.:</b> @Html.DropDownList("MawbId", (IEnumerable<SelectListItem>)ViewBag.MawbId, "Select Mawb", new { style = "width:175px;height:25px" })
                <input type="submit" value="View" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@using (Html.BeginForm("Index", "CheckList", FormMethod.Get))
{
    <hr />
    <p>
        Find by Mawb No. or Origin: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" />
    </p>
}
<table class="table table-bordered">
    <tr>
        <th>
            @Html.ActionLink("Mawb No", "Index", new { sortOrder = ViewBag.MawbSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.Label("Port Of Origin")
        </th>
        <th>
            @Html.Label("Port Of Destination")
            @*@Html.DisplayNameFor(model => model.PortOfDest)*@
        </th>
        <th>
            @Html.Label("Total Package")
            @*@Html.DisplayNameFor(model => model.TotalPkg)*@
        </th>
        <th>
            @Html.Label("Gross Weight")
            @*@Html.DisplayNameFor(model => model.GrossWeight)*@
        </th>
        <th>
            @Html.Label("Item Desc")
            @*@Html.DisplayNameFor(model => model.ItemDesc)*@
        </th>
     
        <th>
            @Html.Label("Shipment Type")
            @*@Html.DisplayNameFor(model => model.ShipmentType)*@
        </th>
        <th>
            @Html.Label("Transmit Status")
            @*@Html.DisplayNameFor(model => model.IsSubmitted)*@
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MawbNo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PortOfOrg)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PortOfDest)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalPkg)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GrossWeight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ItemDesc)
            </td>
          
            <td>
                @Html.DisplayFor(modelItem => item.ShipmentType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsSubmitted)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.Id })
 
            </td>
        </tr>
    }


</table>
<br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}