StarAirEdi/Controllers/HawbController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using StarAirEdi.Models;
using PagedList;

namespace StarAirEdi.Controllers
{
    [Authorize]
    public class HawbController : Controller
    {
        private StarEdiAirEntities db = new StarEdiAirEntities();
        DateTime limitDate = DateTime.Now.AddDays(-10);

        // GET: /Hawb/
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            var hawbs = db.Hawbs.Include(h => h.Mawb);
            var profileData = (UserProfileSessionData)Session["UserProfile"];
            if (profileData != null)
            {
                hawbs = hawbs.Where(p => p.CreatedBy == profileData.UserId && p.CreatedOn > limitDate);
                ViewBag.CurrentSort = sortOrder;
                ViewBag.MawbSortParm = String.IsNullOrEmpty(sortOrder) ? "HawbNo_Desc" : "";

                if (searchString != null)
                {
                    page = 1;
                }
                else
                {
                    searchString = currentFilter;
                    hawbs = hawbs.Where(p => p.CreatedBy == profileData.UserId);
                }

                ViewBag.CurrentFilter = searchString;

                if (!String.IsNullOrEmpty(searchString))
                {
                    hawbs = hawbs.Where(s => s.HawbNo.Contains(searchString)
                                            || s.Mawb.MawbNo.Contains(searchString));
                }
                switch (sortOrder)
                {
                    case "HawbNo_Desc":
                        hawbs = hawbs.OrderByDescending(s => s.HawbNo);
                        break;
                    default:
                        hawbs = hawbs.OrderByDescending(s => s.CreatedOn);
                        break;
                }
                int pageSize = 8;
                int pageNumber = (page ?? 1);

                return View(hawbs.ToPagedList(pageNumber, pageSize));
                //return View(mawbs.ToList());
            }
            else
            {
                return RedirectToAction("Location", "Home");
            }

        }

        // GET: /Hawb/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hawb hawb = db.Hawbs.Find(id);
            if (hawb == null)
            {
                return HttpNotFound();
            }
            return View(hawb);
        }

        // GET: /Hawb/Create
        public ActionResult Create()
        {
            var profileData = (UserProfileSessionData)Session["UserProfile"];
            if (profileData == null)
                return RedirectToAction("Location", "Home");
            var mawbs = db.Mawbs.Where(p => p.CreatedBy == profileData.UserId && p.IsSubmitted==false && p.CreatedOn > limitDate);
            ViewBag.MawbId1 = new SelectList(mawbs.OrderByDescending(s => s.CreatedOn), "Id", "MawbNo", TempData["MawbId"]);
            return View();
        }

        // POST: /Hawb/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,MawbId,HawbNo,PortOfOrigin,PortOfDest,NoOfPkg,Weight,Description,MessageType,HawbDate,ShipmentType")] Hawb hawb)
        {
            if (ModelState.IsValid)
            {
                var profileData = (UserProfileSessionData)Session["UserProfile"];
                if (profileData == null)
                    return RedirectToAction("Location", "Home");
                if (db.Mawbs.Find(hawb.MawbId).MawbNo.Contains("A"))
                {
                    hawb.MessageType = "S";
                    hawb.ShipmentType = "T";
                }
                hawb.CreatedBy = profileData.UserId;
                hawb.CreatedOn = DateTime.Now;
                db.Hawbs.Add(hawb);
                db.SaveChanges();
                var totalPkg=db.Hawbs.Where(h=>h.MawbId==hawb.MawbId).Sum(s=>s.NoOfPkg);
                if(db.Mawbs.Find(hawb.MawbId).TotalPkg <= totalPkg)
                      return RedirectToAction("Index");
            }
            TempData["MawbId"] = hawb.MawbId;
            //ViewBag.MawbId = new SelectList(db.Mawbs.OrderByDescending(s => s.CreatedOn), "Id", "MawbNo", hawb.MawbId);
            return RedirectToAction("Create"); ;
        }

        // GET: /Hawb/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hawb hawb = db.Hawbs.Find(id);
            if (hawb == null)
            {
                return HttpNotFound();
            }
            ViewBag.MawbId1 = new SelectList(SelectListMawb((bool)hawb.Mawb.IsSubmitted), "Id", "MawbNo", hawb.MawbId);
            return View(hawb);
        }

        // POST: /Hawb/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,MawbId,HawbNo,PortOfOrigin,PortOfDest,NoOfPkg,Weight,Description,MessageType,HawbDate,ShipmentType")] Hawb hawb)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hawb).State = EntityState.Modified;
                var profileData = (UserProfileSessionData)Session["UserProfile"];
                hawb.CreatedBy = profileData.UserId;
                hawb.CreatedOn = DateTime.Now;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MawbId = new SelectList(SelectListMawb((bool)hawb.Mawb.IsSubmitted), "Id", "MawbNo", hawb.MawbId);
            return View(hawb);
        }


        // GET: /Hawb/Amend/5
        public ActionResult Amend(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hawb hawb = db.Hawbs.Find(id);
            if (hawb == null)
            {
                return HttpNotFound();
            }
            var mawb = db.Mawbs.Where(h => h.MawbNo.Contains(hawb.Mawb.MawbNo + "-A")).OrderByDescending(s => s.CreatedOn).FirstOrDefault();
            if (mawb != null)
            {
                ViewBag.MawbId = new SelectList(SelectListMawb(false), "Id", "MawbNo", mawb.Id);
            }
            else
            {
                ViewBag.MawbId = new SelectList(SelectListMawb(false), "Id", "MawbNo");
                ModelState.AddModelError("", "Ameded MAWB is not exists! create a MAWB amendment transaction");
            }
            return View(hawb);
        }

        // POST: /Hawb/Amend/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Amend([Bind(Include = "Id,MawbId,HawbNo,PortOfOrigin,PortOfDest,NoOfPkg,Weight,Description,MessageType,HawbDate,ShipmentType")] Hawb hawb)
        {
            if (ModelState.IsValid)
            {
                var mawb=db.Mawbs.Find(hawb.MawbId);
                //var mawb = db.Mawbs.Where(h => h.MawbNo.Contains(mawbno)).FirstOrDefault<Mawb>();
                if (hawb.HawbNo.Contains("A"))
                {
                    var profileData = (UserProfileSessionData)Session["UserProfile"];
                    db.Entry(hawb).State = EntityState.Modified;
                    hawb.CreatedBy = profileData.UserId;
                    hawb.CreatedOn = DateTime.Now;
                    Int32 status = db.SaveChanges();
                }
                else if (db.Hawbs.Where(h=>h.HawbNo ==hawb.HawbNo).Count()==1)
                {
                    var profileData = (UserProfileSessionData)Session["UserProfile"];
                    hawb.MawbId = mawb.Id;
                    hawb.HawbDate = mawb.TransmittedOn;
                    hawb.CreatedBy = profileData.UserId;
                    hawb.MessageType = "A";
                    hawb.ShipmentType = "T";
                    hawb.CreatedOn = DateTime.Now;
                    db.Hawbs.Add(hawb);
                    Int32 status = db.SaveChanges();
                }
                else
                {
                    var profileData = (UserProfileSessionData)Session["UserProfile"];
                    hawb.Id = 0;
                    hawb.MawbId = mawb.Id;
                    //hawb.HawbDate = mawb.TransmittedOn;
                    hawb.CreatedBy = profileData.UserId;
                    hawb.MessageType = "S";
                    hawb.ShipmentType = "T";
                    hawb.CreatedOn = DateTime.Now;
                    db.Hawbs.Add(hawb);
                    Int32 status = db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            ViewBag.MawbId = new SelectList(SelectListMawb(true), "Id", "MawbNo", hawb.MawbId);
            return View(hawb);
        }

        // GET: /Hawb/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hawb hawb = db.Hawbs.Find(id);
            if (hawb == null)
            {
                return HttpNotFound();
            }
            return View(hawb);

StarAirEdi/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Star Edi Services</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    
</head>
<body>
    <div id="menu" class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", null, new { @class = "navbar-brand"})
                @*, style = "background: url('" + Url.Content("~/images/logo.jpg") + "') no-repeat center right; display:block; height:40px; width:120px;"*@ 
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("MAWB", "Index", "Mawb")</li>
                        <li>@Html.ActionLink("HAWB", "Index", "Hawb")</li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Transmission<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Transmit", "Create", "SubmitConsol")</li>
                                <li>@Html.ActionLink("ReTransmit", "ReTransmit", "SubmitConsol")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Report<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Checklist", "Index", "Checklist")</li>    
                                <li>@Html.ActionLink("Account Statement", "AccountStatement", "Checklist")</li>
                            </ul>
                        </li>
                        <li>@Html.ActionLink("Location", "Location", "Home")</li>
                        <li>@Html.ActionLink("Can/Do", "Index", "DeliveryOrder")</li>
                        @if(User.IsInRole("SuperAdmin"))
                        {
                        <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Register Role", "Index", "Roles")</li>
                                <li>@Html.ActionLink("Register User", "Register", "Account")</li>
                                <li>@Html.ActionLink("Register Profile", "Index", "Profile")</li>
                                <li>@Html.ActionLink("Account Statement By User", "AccountStatementUser", "Checklist")</li>
                            </ul>
                        </li>
                        }
                    </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        @if (Request.RequestContext.RouteData.Values["controller"].ToString() != "Checklist" && Request.RequestContext.RouteData.Values["action"].ToString() != "PrintDeliveryOrder")
        { 
        <footer>
            <p>&copy; @DateTime.Now.Year - Star Edi Services</p>
        </footer>
        }
    </div>
    <script src="@Url.Content("~/Scripts/jquery-1.10.2.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")" type="text/javascript"></script> 
    
    <!-- jQuery UI CSS Reference -->
    <link href="@Url.Content("~/Content/themes/base/minified/jquery-ui.min.css")" rel="stylesheet" />
    <!-- Required jQuery and jQuery UI Javascript references -->
    <script src="@Url.Content("~/Scripts/jquery-ui-1.11.4.min.js")"></script>
    <script>

        //$(function () {
        //    // This will make every element with the class "date-picker" into a DatePicker element
        //    $('.date-picker').datepicker({ dateFormat: 'dd/mm/yy', changeYear: false });
        //})

        $(function () {
            $.validator.addMethod('date',
            function (value, element) {
                if (this.optional(element)) {
                    return true;
                }
                var ok = true;
                try {
                    $.datepicker.parseDate('dd/mm/yy', value);
                }
                catch (err) {
                    ok = false;
                }
                return ok;
            });
            $(".date-picker").datepicker({ dateFormat: 'dd/mm/yy', changeYear: false });
        });
    </script>


    @*@Scripts.Render("~/bundles/jquery")*@
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    
</body>
</html>